package projectEuler;

import java.util.Scanner;

public class ProjectEuler2 {
  
  /**
   * This problem is a programming version of Problem 2 from projecteuler.net
   * 
   * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with  and , the first 10 terms will be:
   *                    1, 2, 3, 5, 8, 13, 21, 34, 55, 89,...
   * By considering the terms in the Fibonacci sequence whose values do not exceed , find the sum of the even-valued terms.
   *
   *Input Format
   *
   *First line contains T that denotes the number of test cases. This is followed by T lines, each containing an integer, N.
   *
   *Constraints
   *
   *  1<=T<=10^5
   *  10<=N<=4*10^6
   *  
   *Output Format
   *
   *Print the required answer for each test case.
   *
   *Sample Input 0
   *
   *  2
   *  10
   *  100
   *Sample Output 0
   *
   *  10
   *  44
   *Explanation 0
   *
   *For 10, we have {2,8}, sum is 10.
   *For 100, we have {2,8,34}, sum is 44.
   * */
  
  public static void main(String[] args) {
    Scanner in = new Scanner(System.in);
    int t = in.nextInt();
    for(int a0 = 0; a0 < t; a0++){
      long n = in.nextLong();
      long a=0,b=2,sum=0;
      while(b<n)
      {
        b = 4 * b + a;
        a = (b-a) / 4;
        sum+=a;
      }
    System.out.println(sum);
    }
    in.close();
  }
}